name: test & build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: test
        run: go test ./...
      - name: build
        run: go build ./cmd/extra-gen
